version: "3.7"

services:
    kruhlmann.dev:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: kruhlmann.dev
        restart: unless-stopped
        ports:
            - 3000:8987
