name: Docker build

on:
  push:

jobs:
    lint:
      name: Shellcheck
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install shellcheck
        run: sudo apt-get install --assume-yes --no-install-recommends shellcheck
      - name: Run shellcheck
        run: shellcheck -x scripts/* 

    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
          with:
            lfs: true
        - name: Build docker image
          run: docker build --cache-from $IMAGE_NAME -t $PUBLIC_TAG -t $PRIVATE_TAG -f docker/Dockerfile .

    publish:
      needs: build
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
        - name: Authenticate against public registry
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.PDOCKER_PASS }}
        - name: Publish to hub.docker.com
          run: docker push $PUBLIC_TAG

env:
  IMAGE_NAME: localhost/kruhlmann.dev
  PUBLIC_TAG: kruhlmann/kruhlmann.dev:onbuild
  PRIVATE_TAG: registry.kruhlmann.dev/kruhlmann.dev:onbuild
