name: Linting
on:
    push:
        branches:
            - "*"

jobs:
    compliance:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: dependencies
              run: make node_modules
            - name: lint
              run: make lint
            - name: notes
              run: make notes
            - name: disabled-rules
              run: make disables
