name: Linting
on:
    push:
        branches:
            - "*"

jobs:
    compliance:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: make node_modules
            - name: Lint codebase
              run: make lint
            - name: Print notes like TODO or HACK
              run: make notes
            - name: Print the list of disabled eslint rules
              run: make disables
