name: Docker build & publish

on:
    push:
        branches:
            - "master"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@master
            with:
                lfs: true
          - name: Build docker image
            run: |
                docker build --cache-from $IMAGE_NAME -t $PUBLIC_TAG -t $PRIVATE_TAG -f docker/Dockerfile .
    publish_private:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Authenticate against private registry
              uses: docker/login-action@v1
              with:
                  login-server: registry.kruhlmann.dev
                  username: ${{ secrets.PRIVATE_DOCKER_USER }}
                  password: ${{ secrets.PRIVATE_DOCKER_PASS }}
            - name: Publish to registry.kruhlmann.dev
              run: |
                  docker push $PRIVATE_TAG
    publish_public:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Authenticate against public registry
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.PDOCKER_PASS }}
            - name: Publish to hub.docker.com
              run: |
                  docker push $PUBLIC_TAG

env:
  IMAGE_NAME: localhost/kruhlmann.dev
  PUBLIC_TAG: kruhlmann/kruhlmann.dev:onbuild
  PRIVATE_TAG: registry.kruhlmann.dev/kruhlmann.dev:onbuild
