name: node

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install
        gem install vstheme2scss
    - name: Build
      run: |
        vstheme2scss -o src/scss/_themes.scss -j src/themes.js src/themes/cobalt.js
        sed -i 's/^\[.*\]$/export default &\;/ src/themes.js
        npm run build
