name: Unit & integration tests

on:
    push:
        branches:
            - "*"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run unit tests
              run: make test-unit
            - name: Run integration tests
              run: make test-integration
            - uses: actions/upload-artifact@v2
              with:
                  name: Test results
                  path: |
                      cypress/screenshots/*.png
                      test-report.xml
                      integration-report.xml
